# Generated by Django 5.1.7 on 2025-03-08 10:01

from django.db import migrations

def insert_holidays(apps,schema_editor):
    TimeSlot=apps.get_model('timescheduingweb','Timeslot')
    TimeSlot(start_time='2025-05-17T00:00:00',
             end_time='2025-05-17T23:59:59',
             description='Labour day').save()
    TimeSlot(start_time='2025-07-11T00:00:00',
             end_time='2025-07-11T23:59:59',
             description='Womens day').save()
    TimeSlot(start_time='2025-08-13T00:00:00',
             end_time='2025-08-13T23:59:59',
             description='National Holiday').save()
    TimeSlot(start_time='2025-02-14T00:00:00',
             end_time='2025-02-14T23:59:59',
             description='Black day').save()



class Migration(migrations.Migration):

    dependencies = [
        ('timeschedulingweb', '0001_initial'),
    ]

    operations = [
    ]
